version: '3'
services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - "3080:3080"
    container_name: api
    volumes:
       - ./api:/api
       - /api/node_modules
  app:
    build:
      context: ./app
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    container_name: app
    volumes:
       - ./app:/app
       - /app/node_modules